[package]
name = "prosody-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rserver"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "^0.6", features = ["async", "lua52", "vendored", "module"] }
tokio = { version = "^1.9", features = ["rt", "rt-multi-thread", "sync", "time", "macros", "net", "io-util"] }
lazy_static = { version ="^1.4" }
tokio-rustls = { version = "^0.22" }
rustls-pemfile = { version = "^0.2" }
log = { version = "^0.4" }
pin-project-lite = { version = "^0.2" }
bytes = { version = "^1" }
